# Load Data

In [272]:
from sklearn.datasets import fetch_20newsgroups

In [273]:
data = fetch_20newsgroups()

In [274]:
data.data[:4]

["From: lerxst@wam.umd.edu (where's my thing)\nSubject: WHAT car is this!?\nNntp-Posting-Host: rac3.wam.umd.edu\nOrganization: University of Maryland, College Park\nLines: 15\n\n I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.\n\nThanks,\n- IL\n   ---- brought to you by your neighborhood Lerxst ----\n\n\n\n\n",
 "From: guykuo@carson.u.washington.edu (Guy Kuo)\nSubject: SI Clock Poll - Final Call\nSummary: Final call for SI clock reports\nKeywords: SI,acceleration,clock,upgrade\nArticle-I.D.: shelley.1qvfo9INNc3s\nOrganization: University of Washington\nLines: 11\nNNTP-Posting-Host: carson.u.washington.edu\n\nA fair number of brave souls who upgraded their SI clock oscillator have\nshared their experiences for this poll. Please send a brief message detailing\nyour experiences with the procedure. Top speed attained, CPU rated speed,\nadd on cards and adapters, heat sinks, hour of usage per day, floppy disk\nfunctionality with 800 and 1.4 m floppies are especially requested.\n\nI will be summarizing in the next two days, so please add to the network\nknowledge base if you have done the clock upgrade and haven't answered this\npoll. Thanks.\n\nGuy Kuo <guykuo@u.washington.edu>\n",
 'From: twillis@ec.ecn.purdue.edu (Thomas E Willis)\nSubject: PB questions...\nOrganization: Purdue University Engineering Computer Network\nDistribution: usa\nLines: 36\n\nwell folks, my mac plus finally gave up the ghost this weekend after\nstarting life as a 512k way back in 1985.  sooo, i\'m in the market for a\nnew machine a bit sooner than i intended to be...\n\ni\'m looking into picking up a powerbook 160 or maybe 180 and have a bunch\nof questions that (hopefully) somebody can answer:\n\n* does anybody know any dirt on when the next round of powerbook\nintroductions are expected?  i\'d heard the 185c was supposed to make an\nappearence "this summer" but haven\'t heard anymore on it - and since i\ndon\'t have access to macleak, i was wondering if anybody out there had\nmore info...\n\n* has anybody heard rumors about price drops to the powerbook line like the\nones the duo\'s just went through recently?\n\n* what\'s the impression of the display on the 180?  i could probably swing\na 180 if i got the 80Mb disk rather than the 120, but i don\'t really have\na feel for how much "better" the display is (yea, it looks great in the\nstore, but is that all "wow" or is it really that good?).  could i solicit\nsome opinions of people who use the 160 and 180 day-to-day on if its worth\ntaking the disk size and money hit to get the active display?  (i realize\nthis is a real subjective question, but i\'ve only played around with the\nmachines in a computer store breifly and figured the opinions of somebody\nwho actually uses the machine daily might prove helpful).\n\n* how well does hellcats perform?  ;)\n\nthanks a bunch in advance for any info - if you could email, i\'ll post a\nsummary (news reading time is at a premium with finals just around the\ncorner... :( )\n--\nTom Willis  \\  twillis@ecn.purdue.edu    \\    Purdue Electrical Engineering\n---------------------------------------------------------------------------\n"Convictions are more dangerous enemies of truth than lies."  - F. W.\nNietzsche\n',
 'From: jgreen@amber (Joe Green)\nSubject: Re: Weitek P9000 ?\nOrganization: Harris Computer Systems Division\nLines: 14\nDistribution: world\nNNTP-Posting-Host: amber.ssd.csd.harris.com\nX-Newsreader: TIN [version 1.1 PL9]\n\nRobert J.C. Kyanko (rob@rjck.UUCP) wrote:\n> abraxis@iastate.edu writes in article <abraxis.734340159@class1.iastate.edu>:\n> > Anyone know about the Weitek P9000 graphics chip?\n> As far as the low-level stuff goes, it looks pretty nice.  It\'s got this\n> quadrilateral fill command that requires just the four points.\n\nDo you have Weitek\'s address/phone number?  I\'d like to get some information\nabout this chip.\n\n--\nJoe Green\t\t\t\tHarris Corporation\njgreen@csd.harris.com\t\t\tComputer Systems Division\n"The only thing that really scares me is a person with no sense of humor."\n\t\t\t\t\t\t-- Jonathan Winters\n']

In [275]:
print(data.data[0])

From: lerxst@wam.umd.edu (where's my thing)
Subject: WHAT car is this!?
Nntp-Posting-Host: rac3.wam.umd.edu
Organization: University of Maryland, College Park
Lines: 15

 I was wondering if anyone out there could enlighten me on this car I saw
the other day. It was a 2-door sports car, looked to be from the late 60s/
early 70s. It was called a Bricklin. The doors were really small. In addition,
the front bumper was separate from the rest of the body. This is
all I know. If anyone can tellme a model name, engine specs, years
of production, where this car is made, history, or whatever info you
have on this funky looking car, please e-mail.

Thanks,
- IL
   ---- brought to you by your neighborhood Lerxst ----

In [276]:
data.data[0] += "I'm happy"

In [277]:
import pandas as pd

In [278]:
df = pd.DataFrame(data.data, columns=["text"])
df.head()

                                                text
0  From: lerxst@wam.umd.edu (where's my thing)\nS...
1  From: guykuo@carson.u.washington.edu (Guy Kuo)...
2  From: twillis@ec.ecn.purdue.edu (Thomas E Will...
3  From: jgreen@amber (Joe Green)\nSubject: Re: W...
4  From: jcm@head-cfa.harvard.edu (Jonathan McDow...

In [279]:
for i in range(5):
    print(df['text'][i])

From: lerxst@wam.umd.edu (where's my thing)
Subject: WHAT car is this!?
Nntp-Posting-Host: rac3.wam.umd.edu
Organization: University of Maryland, College Park
Lines: 15

 I was wondering if anyone out there could enlighten me on this car I saw
the other day. It was a 2-door sports car, looked to be from the late 60s/
early 70s. It was called a Bricklin. The doors were really small. In addition,
the front bumper was separate from the rest of the body. This is
all I know. If anyone can tellme a model name, engine specs, years
of production, where this car is made, history, or whatever info you
have on this funky looking car, please e-mail.

Thanks,
- IL
   ---- brought to you by your neighborhood Lerxst ----




I'm happy
From: guykuo@carson.u.washington.edu (Guy Kuo)
Subject: SI Clock Poll - Final Call
Summary: Final call for SI clock reports
Keywords: SI,acceleration,clock,upgrade
Article-I.D.: shelley.1qvfo9INNc3s
Organization: University of Washington
Lines: 11
NNTP-Posting-Host: carson.u.washington.edu

A fair number of brave souls who upgraded their SI clock oscillator have
shared their experiences for this poll. Please send a brief message detailing
your experiences with the procedure. Top speed attained, CPU rated speed,
add on cards and adapters, heat sinks, hour of usage per day, floppy disk
functionality with 800 and 1.4 m floppies are especially requested.

I will be summarizing in the next two days, so please add to the network
knowledge base if you have done the clock upgrade and haven't answered this
poll. Thanks.

Guy Kuo <guykuo@u.washington.edu>

From: twillis@ec.ecn.purdue.edu (Thomas E Willis)
Subject: PB questions...
Organization: Purdue University Engineering Computer Network
Distribution: usa
Lines: 36

well folks, my mac plus finally gave up the ghost this weekend after
starting life as a 512k way back in 1985.  sooo, i'm in the market for a
new machine a bit sooner than i intended to be...

i'm looking into picking up a powerbook 160 or maybe 180 and have a bunch
of questions that (hopefully) somebody can answer:

* does anybody know any dirt on when the next round of powerbook
introductions are expected?  i'd heard the 185c was supposed to make an
appearence "this summer" but haven't heard anymore on it - and since i
don't have access to macleak, i was wondering if anybody out there had
more info...

* has anybody heard rumors about price drops to the powerbook line like the
ones the duo's just went through recently?

* what's the impression of the display on the 180?  i could probably swing
a 180 if i got the 80Mb disk rather than the 120, but i don't really have
a feel for how much "better" the display is (yea, it looks great in the
store, but is that all "wow" or is it really that good?).  could i solicit
some opinions of people who use the 160 and 180 day-to-day on if its worth
taking the disk size and money hit to get the active display?  (i realize
this is a real subjective question, but i've only played around with the
machines in a computer store breifly and figured the opinions of somebody
who actually uses the machine daily might prove helpful).

* how well does hellcats perform?  ;)

thanks a bunch in advance for any info - if you could email, i'll post a
summary (news reading time is at a premium with finals just around the
corner... :( )
--
Tom Willis  \  twillis@ecn.purdue.edu    \    Purdue Electrical Engineering
---------------------------------------------------------------------------
"Convictions are more dangerous enemies of truth than lies."  - F. W.
Nietzsche

From: jgreen@amber (Joe Green)
Subject: Re: Weitek P9000 ?
Organization: Harris Computer Systems Division
Lines: 14
Distribution: world
NNTP-Posting-Host: amber.ssd.csd.harris.com
X-Newsreader: TIN [version 1.1 PL9]

Robert J.C. Kyanko (rob@rjck.UUCP) wrote:
> abraxis@iastate.edu writes in article <abraxis.734340159@class1.iastate.edu>:
> > Anyone know about the Weitek P9000 graphics chip?
> As far as the low-level stuff goes, it looks pretty nice.  It's got this
> quadrilateral fill command that requires just the four points.

Do you have Weitek's address/phone number?  I'd like to get some information
about this chip.

--
Joe Green				Harris Corporation
jgreen@csd.harris.com			Computer Systems Division
"The only thing that really scares me is a person with no sense of humor."
						-- Jonathan Winters

From: jcm@head-cfa.harvard.edu (Jonathan McDowell)
Subject: Re: Shuttle Launch Question
Organization: Smithsonian Astrophysical Observatory, Cambridge, MA,  USA
Distribution: sci
Lines: 23

From article <C5owCB.n3p@world.std.com>, by tombaker@world.std.com (Tom A Baker):
>>In article <C5JLwx.4H9.1@cs.cmu.edu>, ETRAT@ttacs1.ttu.edu (Pack Rat) writes...
>>>"Clear caution & warning memory.  Verify no unexpected
>>>errors. ...".  I am wondering what an "expected error" might
>>>be.  Sorry if this is a really dumb question, but
>
> Parity errors in memory or previously known conditions that were waivered.
>    "Yes that is an error, but we already knew about it"
> I'd be curious as to what the real meaning of the quote is.
>
> tom


My understanding is that the 'expected errors' are basically
known bugs in the warning system software - things are checked
that don't have the right values in yet because they aren't
set till after launch, and suchlike. Rather than fix the code
and possibly introduce new bugs, they just tell the crew
'ok, if you see a warning no. 213 before liftoff, ignore it'.

 - Jonathan

In [280]:
df['text'] = df['text'].str.lower()
df.head()

                                                text
0  from: lerxst@wam.umd.edu (where's my thing)\ns...
1  from: guykuo@carson.u.washington.edu (guy kuo)...
2  from: twillis@ec.ecn.purdue.edu (thomas e will...
3  from: jgreen@amber (joe green)\nsubject: re: w...
4  from: jcm@head-cfa.harvard.edu (jonathan mcdow...

# Cleaning Text Data

In [281]:
import re

## Remove HTML Tags

In [282]:
html_regex = re.compile(r'<.*?>')
def remove_html(text):
    return re.sub(html_regex, '', text)
df['text'] = df['text'].apply(remove_html)
df.head()

                                                text
0  from: lerxst@wam.umd.edu (where's my thing)\ns...
1  from: guykuo@carson.u.washington.edu (guy kuo)...
2  from: twillis@ec.ecn.purdue.edu (thomas e will...
3  from: jgreen@amber (joe green)\nsubject: re: w...
4  from: jcm@head-cfa.harvard.edu (jonathan mcdow...

## Remove Links

In [283]:
link_regex = re.compile(r'https?://\S+|www\.\S+')
def remove_links(text):
    return re.sub(link_regex, '', text)
df['text'] = df['text'].apply(remove_links)
df.head()

                                                text
0  from: lerxst@wam.umd.edu (where's my thing)\ns...
1  from: guykuo@carson.u.washington.edu (guy kuo)...
2  from: twillis@ec.ecn.purdue.edu (thomas e will...
3  from: jgreen@amber (joe green)\nsubject: re: w...
4  from: jcm@head-cfa.harvard.edu (jonathan mcdow...

## Remove Punctuation

In [284]:
from string import punctuation
punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

### Punctuation Removal with Regex

In [285]:
punc_re = re.compile(r"[0-9{}]".format(re.escape(punctuation)))
punc_re

re.compile(r'[0-9!"\#\$%\&\'\(\)\*\+,\-\./:;<=>\?@\[\\\]\^_`\{\|\}\~]',
           re.UNICODE)

### Mail regex

In [286]:
mail_re = re.compile('[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}')

<>:1: SyntaxWarning: "\." is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\."? A raw string is also an option.
<>:1: SyntaxWarning: "\." is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\."? A raw string is also an option.
/tmp/ipykernel_86606/135190596.py:1: SyntaxWarning: "\." is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\."? A raw string is also an option.
  mail_re = re.compile('[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}')

In [287]:
import random

random_num = int(random.random() * 1000000000)
random_num

139494520

In [288]:
def remove_puns(text):
    mails = mail_re.findall(text)
    for mail in mails:
        text = text.replace(mail,f"{random_num}")
    clean = punc_re.sub('',text)
    for i,mail in enumerate(mails):
        clean = clean.replace(f"{random_num}",mail)
    return clean

In [289]:
df['text'] = df['text'].apply(remove_puns)
df.head()

                                                text
0  from  wheres my thing\nsubject what car is thi...
1  from  guy kuo\nsubject si clock poll  final ca...
2  from  thomas e willis\nsubject pb questions\no...
3  from jgreenamber joe green\nsubject re weitek ...
4  from  jonathan mcdowell\nsubject re shuttle la...

In [290]:
from spellchecker import SpellChecker

spell = SpellChecker(distance=1)  # faster; increase distance for recall
def correct_text(text):
    words = text.split()
    corrected = [spell.correction(w) if w not in spell else w for w in words]
    # filter None fron corrected
    corrected = [w for w in corrected if w is not None]
    return " ".join(corrected)

# usage
s = "hte best way to do cheking"
correct_text(s)

'the best way to do checking'

## Spelling Correction

In [ ]:
# print(df['text'][0])

# df['text'] = df['text'].apply(correct_text)

# print(df['text'][0])

from  wheres my thing
subject what car is this
nntppostinghost racwamumdedu
organization university of maryland college park
lines

 i was wondering if anyone out there could enlighten me on this car i saw
the other day it was a door sports car looked to be from the late s
early s it was called a bricklin the doors were really small in addition
the front bumper was separate from the rest of the body this is
all i know if anyone can tellme a model name engine specs years
of production where this car is made history or whatever info you
have on this funky looking car please email

thanks
 il
    brought to you by your neighborhood lerxst




imim happy

KeyboardInterrupt:

## Stop Words

In [ ]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
stopword = stopwords.words('english')
stopword

[nltk_data] Downloading package stopwords to /home/shk/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [ ]:
def remove_stopwords(text):
    new_text = []
    
    for word in text.split():
        if word in stopword:
            new_text.append('')
        else:
            new_text.append(word)
    return " ".join(new_text)

In [ ]:
str = "the asdf asdf cxzv asdf"
remove_stopwords(str)

' asdf asdf cxzv asdf'

In [ ]:
df['text'] = df['text'].apply(remove_stopwords)
df.head()

                                                text
0   lerxst@wam.umd.edu wheres  thing subject  car...
1   guykuo@carson.u.washington.edu guy kuo subjec...
2   twillis@ec.ecn.purdue.edu thomas e willis sub...
3   jgreenamber joe green subject  weitek p9000 o...
4   jcm@head-cfa.harvard.edu jonathan mcdowell su...

In [ ]:
print(df['text'][0])

from: lerxst@wam.umd.edu (where's  thing) subject:  car  this!? nntp-posting-host: rac3.wam.umd.edu organization: university  maryland, college park lines: 15   wondering  anyone   could enlighten    car  saw   day.    2-door sports car, looked     late 60s/ early 70s.   called  bricklin.  doors  really small.  addition,  front bumper  separate   rest   body.     know.  anyone  tellme  model name, engine specs, years  production,   car  made, history,  whatever info     funky looking car, please e-mail. thanks, - il ---- brought     neighborhood lerxst ----

## Fix Contractions

In [291]:
import contractions


df['text'] = df['text'].apply(contractions.fix)

print(df['text'].iloc[0])

from  where is my thing
subject what car is this
nntppostinghost racwamumdedu
organization university of maryland college park
lines

 i was wondering if anyone out there could enlighten me on this car i saw
the other day it was a door sports car looked to be from the late s
early s it was called a bricklin the doors were really small in addition
the front bumper was separate from the rest of the body this is
all i know if anyone can tellme a model name engine specs years
of production where this car is made history or whatever info you
have on this funky looking car please email

thanks
 il
    brought to you by your neighborhood lerxst




i am happy

## Tokenization

In [292]:
from nltk import WhitespaceTokenizer

tokenizer = WhitespaceTokenizer()

def tokenize(text):
    return tokenizer.tokenize(text)

In [293]:
df['text'] = df['text'].apply(tokenize)
df.head()

                                                text
0  [from, where, is, my, thing, subject, what, ca...
1  [from, guy, kuo, subject, si, clock, poll, fin...
2  [from, thomas, e, willis, subject, pb, questio...
3  [from, jgreenamber, joe, green, subject, re, w...
4  [from, jonathan, mcdowell, subject, re, shuttl...

## Stemming

In [294]:
from nltk.stem.porter import PorterStemmer
from nltk.stem.snowball import SnowballStemmer
from nltk.stem.lancaster import LancasterStemmer
from nltk.stem.regexp import RegexpStemmer as regexp_stemmer
snowball_stemmer = SnowballStemmer('english')
stemmer = PorterStemmer()
lancaster = LancasterStemmer()
regex_stem = regexp_stemmer('ing$|s$|e$|able$', min=4)
words = "he was a police officer and he was running after the thief"
snow = [snowball_stemmer.stem(word) for word in words.split()]
port = [stemmer.stem(word) for word in words.split()]
lancaster_stem = [lancaster.stem(word) for word in words.split()]
reg = [regex_stem.stem(word) for word in words.split()]
print(f''' 
      PorterStemmer : {port}
      
      SnowballStemmer : {snow}
      
      LancasterStemmer : {lancaster_stem}
      
      RegexpStemmer : {reg}
      
      ''')

      PorterStemmer : ['he', 'wa', 'a', 'polic', 'offic', 'and', 'he', 'wa', 'run', 'after', 'the', 'thief']

      SnowballStemmer : ['he', 'was', 'a', 'polic', 'offic', 'and', 'he', 'was', 'run', 'after', 'the', 'thief']

      LancasterStemmer : ['he', 'was', 'a', 'pol', 'off', 'and', 'he', 'was', 'run', 'aft', 'the', 'thief']

      RegexpStemmer : ['he', 'was', 'a', 'polic', 'officer', 'and', 'he', 'was', 'runn', 'after', 'the', 'thief']

In [295]:
# df['text'] = df['text'].apply(lambda text: TextBlob(" ".join(text)).correct().string)

# Lemmatization

In [296]:
from nltk.stem import WordNetLemmatizer
# Intilize Lemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

wordnet_lemmatizer.lemmatize('looked', pos='v')

'look'

In [297]:
def lemmatize(text):
    lem = [wordnet_lemmatizer.lemmatize(word,pos='v') for word in text]
    return lem

In [298]:
df['text'] = df['text'].apply(lemmatize)

In [299]:
df['text'][0]

['from',
 'where',
 'be',
 'my',
 'thing',
 'subject',
 'what',
 'car',
 'be',
 'this',
 'nntppostinghost',
 'racwamumdedu',
 'organization',
 'university',
 'of',
 'maryland',
 'college',
 'park',
 'line',
 'i',
 'be',
 'wonder',
 'if',
 'anyone',
 'out',
 'there',
 'could',
 'enlighten',
 'me',
 'on',
 'this',
 'car',
 'i',
 'saw',
 'the',
 'other',
 'day',
 'it',
 'be',
 'a',
 'door',
 'sport',
 'car',
 'look',
 'to',
 'be',
 'from',
 'the',
 'late',
 's',
 'early',
 's',
 'it',
 'be',
 'call',
 'a',
 'bricklin',
 'the',
 'doors',
 'be',
 'really',
 'small',
 'in',
 'addition',
 'the',
 'front',
 'bumper',
 'be',
 'separate',
 'from',
 'the',
 'rest',
 'of',
 'the',
 'body',
 'this',
 'be',
 'all',
 'i',
 'know',
 'if',
 'anyone',
 'can',
 'tellme',
 'a',
 'model',
 'name',
 'engine',
 'specs',
 'years',
 'of',
 'production',
 'where',
 'this',
 'car',
 'be',
 'make',
 'history',
 'or',
 'whatever',
 'info',
 'you',
 'have',
 'on',
 'this',
 'funky',
 'look',
 'car',
 'please',
 'email',
 'thank',
 'il',
 'bring',
 'to',
 'you',
 'by',
 'your',
 'neighborhood',
 'lerxst',
 'i',
 'be',
 'happy']

TODO: Text Representation
- [ ] Bag of Words
- [ ] TF-IDF
- [ ] Word Embeddings